{{- $fullName := include "init.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-job
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "init.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "init.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy | default "ClusterFirst" }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8}}
      {{- end }}
      serviceAccountName: {{ include "init.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s%s:%s" .Values.image.repository .Values.image.name (coalesce .Values.image.tag .Chart.AppVersion ) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c", "/app/init.sh /data/tenants.json"]
          env: 
            - name: PGDATABASE
              value: {{ .Values.config.dbName | quote }}
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.postgresConfig }}
                  key: META_DB_HOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.postgresConfig }}
                  key: META_DB_PORT
            - name: PGSSLMODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.postgresConfig }}
                  key: META_DB_SSL_MODE
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.postgresSecret }}
                  key: META_DB_ADMIN
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.postgresSecret }}
                  key: META_DB_ADMINPWD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $fullName }}-config-volume
              mountPath: /data/tenants.json
              subPath: tenants.json        

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: {{ $fullName }}-config-volume
          configMap:
            name: {{ $fullName }}-tenant-config
  
  backoffLimit: {{ .Values.backoffLimit }}
