apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "init.fullname" . }}-tenant-config
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "init.labels" . | nindent 4 }}
data: 
  tenants.json: |-
    [
    {{- $first := true -}}
    {{- range $key, $value := .Values.tenants }}
    {{- if not $first -}},{{- end -}}{{- $first = false -}}
    { 
      "id": "{{ $value.id }}",
      "name": "{{ $value.name }}",
      "key": {{ $value.key }},
      "dcu": {{ $value.dcu }}
    }
    {{- end }}
    ]
