# Default values for templates

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

##########################################################################


# tenant identification, or empty for shared deployment
tenant:
  # cloud tenant ID
  id: "00000000-0000-0000-0000-000000000000"
  # cloud tenant SID (like 0001)
  sid: "0000"

# deployment parameters
deployment:
  # deployment type: local|azure (TBD more)
  type: local

config:
  # DB configuration map name
  postgresConfig: ""
  # DB secret name
  postgresSecret: ""
  # DB name
  dbName: pulse
  # Redis config name
  redisConfig: ""
  # Redis secret name
  redisSecret: ""

##########################################################################

# container image common settings
image:
  tag: ""
  pullPolicy: IfNotPresent
  repository: ""

imagePullSecrets: []

##########################################################################

podAnnotations: {}

podSecurityContext:
  runAsUser: 500
  runAsGroup: 500
  fsGroup: 500

priorityClassName: ""

# you can configure nodeSelector if needed
nodeSelector: {}

# tolerations settings
tolerations: {}

##########################################################################

# configuration for the Collector container
collector:
  # container image settings
  image:
    name: collector
  # application parameters
  params:
    # add POD index to the application name
    selectAppByIndex: false
    # Application name on the Configuration Server
    cfgApp: "pulse-col"
  # Application configuration options
  appOptions:
    # request timeout
    collector_dap_user_property__default__db_request_timeout: "120"
    # database case, leave as is
    collector_dap_user_property__default__dbcase: "any"
    # database type
    collector_dap_user_property__default__dbengine: "postgre"
    # [collector]
    collector__collector__dbthread: "true"
    # [configuration-monitoring]
    collector__configuration_monitoring__check_layout_presence_timeout: "900"
    collector__configuration_monitoring__db_poll_period: "30"
    collector__configuration_monitoring__excluded_objects_propagation_delay: "60"
    collector__configuration_monitoring__metagroup_contents_recheck_delay: "60"
    collector__configuration_monitoring__new_object_delay: "10"
    collector__configuration_monitoring__ods_wait_timeout: "300"
    collector__configuration_monitoring__remove_dynamic_object_delay: "60"
    # [heartbeat]
    collector__heartbeat__heartbeat_folder: /mnt/collector-health
    collector__heartbeat__heartbeat_period: "30"
    # [layout-validation]
    collector__layout_validation__enable_layout_validation: "yes"
    # [limits]
    collector__limits__max_formulas_per_layout: "50"
    collector__limits__max_metagroups_per_layout: "50"
    collector__limits__max_objects_per_layout: "100"
    collector__limits__max_statistics_per_layout: "100"
    # [log]
    collector__log__buffering: "true"
    collector__log__time_format: iso8601
    collector__log__verbose: all
    collector__log__segment: "1 hr"
    collector__log__expire: "3 day"
    collector__log__standard: stdout
    # [log-db]
    collector__log_db__buffering: "true"
    collector__log_db__time_format: iso8601
    collector__log_db__verbose: standard
    collector__log_db__segment: "1 hr"
    collector__log_db__expire: "3 day"
    collector__log_db__standard: stdout
    # [object-name-format]
    collector__object_name_format__AccessResource: "%ObjectName%"
    collector__object_name_format__ACDPosition: "%ObjectName%"
    collector__object_name_format__ACDQueue: "%ObjectName%"
    collector__object_name_format__Agent: "%ObjectName%"
    collector__object_name_format__AgentGroup: "%ObjectName%"
    collector__object_name_format__CallingList: "%ObjectName%"
    collector__object_name_format__Campaign: "%ObjectName%"
    collector__object_name_format__CampaignCallingList: "%ObjectName%"
    collector__object_name_format__CampaignGroup: "%ObjectName%"
    collector__object_name_format__Cellular: "%ObjectName%"
    collector__object_name_format__Chat: "%ObjectName%"
    collector__object_name_format__CoBrowse: "%ObjectName%"
    collector__object_name_format__CommDN: "%ObjectName%"
    collector__object_name_format__CP: "%ObjectName%"
    collector__object_name_format__Data: "%ObjectName%"
    collector__object_name_format__DestinationLabel: "%ObjectName%"
    collector__object_name_format__DN: "%ObjectName%"
    collector__object_name_format__DNGroup: "%ObjectName%"
    collector__object_name_format__EAPort: "%ObjectName%"
    collector__object_name_format__Email: "%ObjectName%"
    collector__object_name_format__Extension: "%ObjectName%"
    collector__object_name_format__ExtRoutingPoint: "%ObjectName%"
    collector__object_name_format__FAX: "%ObjectName%"
    collector__object_name_format__GVPDID: "%ObjectName%"
    collector__object_name_format__Mixed: "%ObjectName%"
    collector__object_name_format__Music: "%ObjectName%"
    collector__object_name_format__Place: "%ObjectName%"
    collector__object_name_format__PlaceGroup: "%ObjectName%"
    collector__object_name_format__RoutingPoint: "%ObjectName%"
    collector__object_name_format__RoutingQueue: "%ObjectName%"
    collector__object_name_format__RoutingStrategy: "%ObjectName%"
    collector__object_name_format__Script: "%ObjectName%"
    collector__object_name_format__ServiceNumber: "%ObjectName%"
    collector__object_name_format__StagingArea: "%ObjectName%"
    collector__object_name_format__Switch: "%ObjectName%"
    collector__object_name_format__Tenant: "%ObjectName%"
    collector__object_name_format__TieLine: "%ObjectName%"
    collector__object_name_format__TieLineGroup: "%ObjectName%"
    collector__object_name_format__Trunk: "%ObjectName%"
    collector__object_name_format__TrunkGroup: "%ObjectName%"
    collector__object_name_format__Video: "%ObjectName%"
    collector__object_name_format__VirtACDQueue: "%AliasOrNumber%"
    collector__object_name_format__VirtRoutingPoint: "%ObjectName%"
    collector__object_name_format__VoiceMail: "%ObjectName%"
    collector__object_name_format__VoIP: "%ObjectName%"
    collector__object_name_format__VoIPService: "%ObjectName%"
    collector__object_name_format__Workbin: "%ObjectName%"
    collector__object_name_format__Workflow: "%ObjectName%"
    # [output]
    collector__output__collector_snapshot_log_level: error
    collector__output__max_output_interval: "3600"
    collector__output__min_output_interval: "3"
    collector__output__snapshot_log_level: Info
    # [parallel-processing]
    collector__parallel_processing__snapshot_builder_worker_thread_count: "2"
    collector__parallel_processing__stat_data_processing_thread_pool_size: "4"
    collector__parallel_processing__use_multiple_stat_data_processing_threads: "yes"
    # [scripting]
    collector__scripting__definition_script_execution_timeout: "45"
    collector__scripting__formula_script_execution_timeout: "5"
    collector__scripting__init_script_execution_timeout: "60"
    collector__scripting__js_lib_path: ./jslib/standard
    collector__scripting__js_modules: collector.js,cfglib.js,statlib.js,gts.js
    collector__scripting__stop_compute_formula_threshold_for_snapshot: "3"
    # [statistic-request-handling]
    collector__statistic_request_handling__always_use_statserver_newapi: "yes"
    collector__statistic_request_handling__data_source_choice_strategy: local
    collector__statistic_request_handling__optimize_statistic_requests: "yes"
    collector__statistic_request_handling__statserver_batch_size: "500"
    collector__statistic_request_handling__statserver_profiles_timeout: "600"
    collector__statistic_request_handling__suspend_statistic_notifications_for_paused_layouts: "no"
    collector__statistic_request_handling__verbose_request_statistics: "false"
    # [transport-file]
    collector__transport_file__disabled: "true"
    # [transport-aeron]
    collector__transport_aeron__disabled: "true"
    # [transport-redis]
    collector__transport_redis__disabled: "false"
    collector__transport_redis__ca_cert: "/etc/ssl/certs/ca-bundle.crt"
    # 24h
    collector__transport_redis__latest_snapshot_expiration_timeout: "86400"
    # 3h
    collector__transport_redis__1_min_snapshot_expiration_timeout: "10800"
    # 12h
    collector__transport_redis__5_min_snapshot_expiration_timeout: "43200"
    # 24h
    collector__transport_redis__15_min_snapshot_expiration_timeout: "86400"
    collector__transport_redis__compression_method: lz4
    collector__transport_redis__connection_timeout: "10"
    collector__transport_redis__lz4_compression_level: "8"
    collector__transport_redis__reconnect_timeout: "10"
    collector__transport_redis__retry_timeout: "5"
    collector__transport_redis__timestamp_difference_thresholds: "1-29=10; 30-60=15; 61+=30"
  # configuraiton of the K8S probes for container
  probes:
    # disabled: true
    startupProbe:
      failureThreshold: 60
      periodSeconds: 10
      timeoutSeconds: 2
    livenessProbe:
      periodSeconds: 20
      timeoutSeconds: 2
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "1Gi"
      # minimal CPU to reserve
      cpu: "2000m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "4Gi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "8000m"
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 500
    runAsGroup: 500
  # list of volumes to mount to containers
  volumeMounts:
  - mountPath: /mnt/collector-health
    name: collector-health

##########################################################################

# configuration for the StatServer container
statserver:
  # container image settings
  image:
    name: ss
  # application parameters
  params:
    # add POD index to the application name
    selectAppByIndex: true
    # Application name on the Configuration Server
    # Auto generate if empty
    cfgApp: ""
    # Port number of the upstream Interaction Server
    ixnPort: 7120
    # Port number of the upstream LDS
    ldsPort: 8000
  # ports exposed outside by container
  ports:
    default: 2060
    http: 9193
  # configuraiton of the K8S probes for container
  probes:
    # disabled: true
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      periodSeconds: 20
    readinessProbe:
      periodSeconds: 20
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "1Gi"
      # minimal CPU to reserve
      cpu: "1000m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "4Gi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "4000m"
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 500
    runAsGroup: 500
  # list of volumes to mount to containers
  volumeMounts:
  - mountPath: /mnt/statserver-backup
    name: statserver-backup

##########################################################################

# configuration for the Heartbeat container
heartbeat:
  # container image settings
  image:
    name: nginx
    tag: 1.19.0
    pullPolicy: IfNotPresent
  # ports exposed outside by container
  ports:
    default: 80
  # configuraiton of the K8S probes for container
  probes:
    # disabled: true
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      periodSeconds: 20
    readinessProbe:
      periodSeconds: 20
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "64Mi"
      # minimal CPU to reserve
      cpu: "250m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "1Gi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "500m"
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 0
    # runAsGroup: 500
  # list of volumes to mount to containers
  volumeMounts:
  - mountPath: /usr/share/nginx/html
    name: collector-health

##########################################################################

# configuration for the Heartbeat container initializer
heartbeatInit:
  # container image settings
  image:
    name: busybox
    tag: "1.28"
    pullPolicy: IfNotPresent
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 0
    # runAsGroup: 500
  # list of volumes to mount to containers
  volumeMounts:
  - mountPath: /usr/share/nginx/html
    name: collector-health

##########################################################################

# configuration for the monitor sidecar container
monitorSidecar:
  # container image settings
  image:
    name: monitor_dcu_push_agent
  # application parameters
  params:
    # application metrics polling interval
    pollPeriod: 30
    # initial polling delay
    initialDelay: 10
    # Prometheus push gateway URL
    pushGateUrl: http://prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "128Mi"
      # minimal CPU to reserve
      cpu: "128m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "256Mi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "256m"
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 500
    runAsGroup: 500

##########################################################################

# definitions of volumes
# used for storage that does not support dynamic volume provisioning (ex. emptyDir)
volumes:
  # collectorHealth is a non-persistent storage for collector health data
  # used to store Collector health state (aka heartbeat) files
  collectorHealth:
    name: collector-health
    emptyDir: {}

# volumeClaims contains presistent volume claims for services
# All available storage classes can be found here:
# https://github.com/genesysengage/tfm-azure-core-aks/blob/master/k8s-module/storage.tf
volumeClaims:
  # statserverBackup is storage for statserver backup data
  statserverBackup:
    name: statserver-backup
    accessModes:
    - ReadWriteOnce
    # capacity is storage capacity
    capacity: "1Gi"
    # class is storage class. Must be set explicitly.
    class: files-standard-zrs-retain
