# Helm chart values overrides only for Azure Prod001 westus2

tenant: ""

env:
  GWS_HOST: gws.api01-westus2.prod001.genesysengage.com
  GWS_PORT: 80

ingress:
  enabled: true
  annotations: {}
  domain: nlb01-westus2.prod001.genesysengage.com
  hosts:
    - host: pulse-advance.nlb01-westus2.prod001.genesysengage.com
      paths: [/]
  tls:
    # Each ingress should have a unique secretName, PECAZURE-1482
    - secretName:
      hosts:
        - pulse-advance.nlb01-westus2.prod001.genesysengage.com

gateway:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx01-internal
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
  hosts:
    - host: pulse-advance.api01-westus2.prod001.genesysengage.com
      paths: [/]
  tls:
    # Each ingress should have a unique secretName, PECAZURE-1482
    - secretName:
      hosts:
        - pulse-advance.api01-westus2.prod001.genesysengage.com
