# Default values for templates

# tenant identification, or empty for shared deployment
tenant:
  # cloud tenant ID
  id: "00000000-0000-0000-0000-000000000000"
  # cloud tenant SID (like 0001)
  sid: "0000"

# deployment parameters
deployment:
  # deployment type: local|azure (TBD more)
  type: local

# configuration for the Configuration Server Proxy container
csproxy:
  image:
    name: cs_proxy
  # application parameters
  params:
    # add POD index to the application name
    selectAppByIndex: false
    # Application name on the Configuration Server
    cfgApp: "pulse-csp"
    # Hostname of the Configuration Server
    # If empty, use hostname based on naming conventions
    cfgHost: ""
    # Port number of the upstream Configuration Server
    cfgPort: 8888
    # ADDP trace Mode
    addpTraceMode: both
    # ADDP local timeout
    addpLocalTimeout: 180
    # ADDP remote timeout
    addpRemoteTimeout: 190
  # ports exposed outside by container
  ports:
    default: 8888
  # configuraiton of the K8S probes for container
  probes:
    cfgApp: CloudCluster
    cfgAppType: 107
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
      timeoutSeconds: 2
    livenessProbe:
      periodSeconds: 20
      timeoutSeconds: 2
    readinessProbe:
      periodSeconds: 20
      timeoutSeconds: 2
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "1Gi"
      # minimal CPU to reserve
      cpu: "1000m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "4Gi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "4000m"
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    runAsUser: 500
    runAsGroup: 500

# dns config
# https://intranet.genesys.com/display/AZURE/DNS+-+Kubernetes+pod+spec+configuration
dnsConfig:
  options:
    - name: ndots
      value: "3"
