{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "pulse.fullname" . }}-ingress
spec:
  podSelector:
    matchLabels:
      {{- include "pulse.selectorLabels" . | nindent 6 }}
  ingress:
{{- if .Values.monitoring.enabled }}
  - from:
    - namespaceSelector:
        matchLabels:
          service: monitoring
    ports:
    - port: {{ .Values.service.managementPort }}
      protocol: TCP
{{- end }}
  - ports:
    - port: {{ .Values.options.port }}
      protocol: TCP
    - port: {{ .Values.service.port }}
      protocol: TCP
  policyTypes:
  - Ingress
{{- end }}
