apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulse.fullname" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.managementPort }}
      targetPort: management-port
      protocol: TCP
      name: management-port
  {{- if .Values.debug.enabled }}
    - port: {{ .Values.service.debugPort }}
      targetPort: debug-port
      protocol: TCP
      name: debug-port
  {{- end }}
  selector:
    {{- include "pulse.selectorLabels" . | nindent 4 }}
