{{- if .Values.gateway.enabled -}}
{{- $fullName := include "pulse-manage-agents.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-gateway
  labels:
    {{- include "pulse-manage-agents.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gateway.tls }}
  tls:
    {{- range .Values.gateway.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- else  }}
      secretName: {{ $fullName }}-gateway-tls-secret
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
      {{- range .Values.gateway.hosts }}
      - host: {{ .host | quote }}
        http:
          paths:
            {{- range .paths }}
            - path: {{ . }}
              backend:
                serviceName: {{ $fullName }}
                servicePort: {{ $svcPort }}
            {{- end }}
    {{- end }}
  {{- end }}
