{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pulse-manage-agents.fullname" . }}-allow-prometheus-scrape-pods
spec:
  podSelector:
    matchLabels:
      {{- include "pulse-manage-agents.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: monitor
    from:
      #Prometheus
    - podSelector:   # this is section that allows prometheus pods in monitoring namespaces to pull metrics from service team's pods with label service and value voice
        matchLabels:
          service: monitoring
          servicename: prometheus
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              namespace: gws
        - podSelector:
            matchLabels:
              gws-infra: gws-service-proxy
    - to: []
    {{ if .Values.networkPolicies.egressports }}
      ports:
        {{- toYaml .Values.networkPolicies.egressports | nindent 8 }}
      {{ end }}
  {{- end }}
