{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pulse-manage-agents.serviceAccountName" . }}
  labels:
{{ include "pulse-manage-agents.labels" . | indent 4 }}
{{- end -}}
