{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pulse-manage-agents.fullname" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pulse-manage-agents.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pulse-manage-agents.selectorLabels" . | nindent 8 }}
  endpoints:
    - port: monitor
      interval: 30s
  {{- end }}
