{
 "title": "Backend / JVM",
 "tags": [
  "pulse",
  "backend"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "{{ .Release.Namespace }}" },
   { "name": "CHART", "label": "Chart", "query": "{{ .chart }}" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"}) /\nsum by (pod) (jvm_memory_max_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"}) *\n100",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_threads_states_threads{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\", state=\"blocked\"})",
     "legendFormat": "Blocked: {{`{{pod}}`}}"
    },
    {
     "expr": "sum by (pod) (jvm_threads_states_threads{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\", state=\"waiting\"})",
     "legendFormat": "Waiting: {{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Hikari Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (hikaricp_connections_active{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}