{
 "title": "Backend / Requests",
 "tags": [
  "pulse",
  "backend"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "{{ .Release.Namespace }}" },
   { "name": "CHART", "label": "Chart", "query": "{{ .chart }}" }
  ]
 },
 "panels": [
  {
   "title": "Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_server_requests_seconds_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"}[5m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Max Avg Requests Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (\nrate(http_server_requests_seconds_sum{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"}[5m]) /\nrate(http_server_requests_seconds_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\"}[5m])\n)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Errors 4xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_server_requests_seconds_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\", status=~\"4.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_server_requests_seconds_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-[^-]+-[^-]{5}$\", status=~\"5.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}