{{/* vim: set filetype=mustache: */}}

{{/*
Declare CSI volume containing secret with the provided name
https://intranet.genesys.com/display/AZURE/Sharing+Secrets+Across+Teams
*/}}
{{- define "common.secrets.secretVolume" -}}
- name: {{ . }}
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: keyvault-pulse-{{ . }}
{{- end }}

{{- define "common.secrets.teamSecretVolume" -}}
{{- include "common.secrets.secretVolume" "pulse-team-secret" }}
{{- end }}

{{- define "common.secrets.gwsSecretVolume" -}}
{{- include "common.secrets.secretVolume" "pulse-gws-secret" }}
{{- end }}

{{/*
Mount CSI volume containing secret with the provided name
https://intranet.genesys.com/display/AZURE/Sharing+Secrets+Across+Teams
*/}}
{{- define "common.secrets.secretVolumeMount" -}}
- mountPath: /data/secret/{{ . }}
  name: {{ . }}
  readOnly: true
{{- end }}

{{- define "common.secrets.teamSecretVolumeMount" -}}
{{- include "common.secrets.secretVolumeMount" "pulse-team-secret" }}
{{- end }}

{{- define "common.secrets.gwsSecretVolumeMount" -}}
{{- include "common.secrets.secretVolumeMount" "pulse-gws-secret" }}
{{- end }}
 
{{- define "common.secrets.injectDBUser" -}}
- name: {{ . }}
  value: /data/secret/pulse-team-secret/meta-db-admin
{{- end }}

{{- define "common.secrets.injectDBPassword" -}}
- name: {{ . }}
  value: /data/secret/pulse-team-secret/meta-db-adminpwd
{{- end }}

{{- define "common.secrets.injectRedisPassword" -}}
- name: {{ . }}
  value: /data/secret/pulse-team-secret/redis-key
{{- end }}

{{- define "common.secrets.injectClientId" -}}
- name: {{ . }}
  value: /data/secret/pulse-gws-secret/gws-client-id 
{{- end }}

{{- define "common.secrets.injectClientSecret" -}}
- name: {{ . }}
  value: /data/secret/pulse-gws-secret/gws-client-secret
{{- end }}


