# Default values for init-tenant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

backoffLimit: 0

image:
  name: init
  tag: ""
  pullPolicy: IfNotPresent
  repository: ""

config:
  postgresConfig: ""
  postgresSecret: ""
  dbName: pulse

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: default

podAnnotations: {}

podSecurityContext:
  runAsUser: 500
  runAsGroup: 500
  fsGroup: 500

resources: {}

autoscaling:
  enabled: false

priorityClassName: ""

nodeSelector: {}

tolerations: []

affinity: {}
