{
 "title": "LDS / Containers",
 "tags": [
  "pulse",
  "lds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "{{ .Release.Namespace }}" },
   { "name": "CHART", "label": "Chart", "query": "{{ .chart }}" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-.*\"}, pod)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-.*\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (irate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}[2m]))",
     "legendFormat": "Container: {{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "CPU Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}[2m])) /\nsum by (pod, container) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}) *\n100",
     "legendFormat": "Requested: Container: {{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    },
    {
     "expr": "sum by (pod, container) (rate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}[2m])) /\nsum by (pod, container) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}) *\n100",
     "legendFormat": "Limits: Container: {{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"})",
     "legendFormat": "Container: {{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  },
  {
   "title": "Memory Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}) /\nsum by (pod, container) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}) *\n100",
     "legendFormat": "Requested: Container: {{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    },
    {
     "expr": "sum by (pod, container) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}) /\nsum by (pod, container) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container=~\"$Container\"}) *\n100",
     "legendFormat": "Limits: Container: {{`{{container}}`}} (Pod: {{`{{pod}}`}})"
    }
   ]
  }
 ]
}