{
 "title": "LDS / Pods",
 "tags": [
  "pulse",
  "lds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "{{ .Release.Namespace }}" },
   { "name": "CHART", "label": "Chart", "query": "{{ .chart }}" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1 * min by(pod) (kube_pod_status_phase{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",phase=\"Failed\"}) + \n2 * min by(pod) (kube_pod_status_phase{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",phase=\"Pending\"}) + \n3 * min by(pod) (kube_pod_status_phase{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",phase=\"Running\"}) + \n4 * min by(pod) (kube_pod_status_phase{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",phase=\"Succeeded\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Running Instances, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum by (statefulset) (kube_statefulset_status_replicas_ready{namespace=\"$NAMESPACE\",statefulset=\"$DEPLOYMENT_CODE-$CHART-$Tenant\"}) /\nsum by (statefulset) (kube_statefulset_status_replicas{namespace=\"$NAMESPACE\",statefulset=\"$DEPLOYMENT_CODE-$CHART-$Tenant\"}) * 100",
     "legendFormat": "{{`{{statefulset}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "CPU Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container!=\"POD\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}) *\n100",
     "legendFormat": "Requested: {{`{{pod}}`}}"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\",container!=\"POD\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}) *\n100",
     "legendFormat": "Limits: {{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",container!=\"POD\",container!=\"\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"})",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Memory Usage, %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",container!=\"\",container!=\"POD\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}) /\nsum by (pod) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}) * 100",
     "legendFormat": "Requested: {{`{{pod}}`}}"
    },
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$NAMESPACE\",container!=\"\",container!=\"POD\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}) /\nsum by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}) * 100",
     "legendFormat": "Limits: {{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m])))",
     "legendFormat": "RX: {{`{{pod}}`}}"
    },
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m])))",
     "legendFormat": "TX: {{`{{pod}}`}}"
    }
   ]
  }
 ]
}