{
 "title": "LDS / Servers",
 "tags": [
  "pulse",
  "lds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "{{ .Release.Namespace }}" },
   { "name": "CHART", "label": "Chart", "query": "{{ .chart }}" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Senders Number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pulse_lds_senders_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Receivers Number",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pulse_lds_receivers_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Senders: Registered DNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_sender_registered_dns_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{sender}}`}}"
    }
   ]
  },
  {
   "title": "Receivers: Registered DNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_receiver_registered_dns_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{receiver}}`}}"
    }
   ]
  },
  {
   "title": "Senders: Registration Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_sender_registration_errors_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{sender}}`}}"
    }
   ]
  },
  {
   "title": "Receivers: Registration Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_receiver_registration_errors_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{receiver}}`}}"
    }
   ]
  },
  {
   "title": "Senders: Request Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pulse_lds_sender_request_queue_length{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}: {{`{{sender}}`}}"
    }
   ]
  }
 ]
}