{
 "title": "DCU / StatServers",
 "tags": [
  "pulse",
  "dcu",
  "collector",
  "statserver"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "NAMESPACE", "label": "Namespace", "query": "{{ .Release.Namespace }}" },
   { "name": "DEPLOYMENT_CODE", "label": "Deployment Code", "query": "{{ .Release.Namespace }}" },
   { "name": "CHART", "label": "Chart", "query": "{{ .chart }}" },
   {
    "name": "Tenant",
    "query": "label_values(kube_pod_container_info{namespace=\"$NAMESPACE\", pod=~\"$DEPLOYMENT_CODE-$CHART-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pulse_statserver_server_connected_seconds{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"} > bool 0",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pulse_statserver_clients_number{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Total Received Messages, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(pulse_statserver_messages_received_total_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Total Messages Sent, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(pulse_statserver_messages_sent_total_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Client Received Messages, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,name) (rate(pulse_statserver_client_messages_received_total_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Client Messages Sent, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,name) (rate(pulse_statserver_client_messages_sent_total_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}} -> {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Server Received Messages, pps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,server) (rate(pulse_statserver_server_messages_received_total_count{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}[2m]))",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Server Messages Latency Avg, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "pulse_statserver_server_latency_avg{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Server Messages Latency Min, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "pulse_statserver_server_latency_min{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  },
  {
   "title": "Server Messages Latency Max, s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "pulse_statserver_server_latency_max{namespace=\"$NAMESPACE\",pod=~\"$DEPLOYMENT_CODE-$CHART-$Tenant-.*\"}",
     "legendFormat": "{{`{{pod}}`}} <- {{`{{server}}`}}"
    }
   ]
  }
 ]
}