# Default values for templates

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

##########################################################################

# tenant identification, or empty for shared deployment
tenant:
  # cloud tenant ID
  id: "00000000-0000-0000-0000-000000000000"
  # cloud tenant SID (like 0001)
  sid: "0000"

# deployment parameters
deployment:
  # deployment type: local|azure (TBD more)
  type: local

##########################################################################

# container image common settings
image:
  tag: ""
  pullPolicy: IfNotPresent
  repository: ""

imagePullSecrets: []

##########################################################################

podAnnotations: {}

podSecurityContext:
  runAsUser: 500
  runAsGroup: 500
  fsGroup: 500

priorityClassName: ""

# you can configure nodeSelector if needed
nodeSelector: {}

# tolerations settings
tolerations: {}

##########################################################################

# configuration for the LDS container
lds:
  # container image settings
  image:
    name: lds
  # application parameters
  params:
    # add POD index to the application name
    selectAppByIndex: true
    # Application name on the Configuration Server
    # Auto generate if empty
    cfgApp: ""
    # Port number of the upstream SIP Server
    sipPort: 8000
  # ports exposed outside by container
  ports:
    default: 8000
    http: 8180
  # configuraiton of the K8S probes for container
  probes:
    # disabled: true
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      periodSeconds: 20
    readinessProbe:
      periodSeconds: 20
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "1Gi"
      # minimal CPU to reserve
      cpu: "2000m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "4Gi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "4000m"
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 500
    # runAsGroup: 500

##########################################################################

# configuration for the monitor sidecar container
monitorSidecar:
  # container image settings
  image:
    name: monitor_lds_push_agent
  # application parameters
  params:
    # application metrics polling interval
    pollPeriod: 30
    # initial polling delay
    initialDelay: 10
    # Prometheus push gateway URL
    pushGateUrl: http://prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics
  # resource limits for container
  resources:
    # disabled: true
    # minimum resource requirements to start container
    requests:
      # minimal amount of memory required to start a container
      memory: "128Mi"
      # minimal CPU to reserve
      cpu: "128m"
    # resource limits for containers
    limits:
      # maximum amount of memory a container can use before being evicted
      # by the OOM Killer
      memory: "256Mi"
      # maximum amount of CPU resources that can be used and should be tuned to reflect
      # what the application can effectively use before needing to be horizontally scaled out
      cpu: "256m"
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 500
    # runAsGroup: 500
