groups:
- name: Pulse {{ .chart | title }} Alerts
  rules:
  - alert: {{ include "alertName" (merge (dict "alert" "critical_running_instances") .) }}
    expr: |-
      (
        sum by (statefulset) (kube_statefulset_status_replicas_ready{namespace="{{ .Release.Namespace }}",statefulset=~"{{ include "objectName" . }}-.*"}) /
        sum by (statefulset) (kube_statefulset_status_replicas{namespace="{{ .Release.Namespace }}",statefulset=~"{{ include "objectName" . }}-.*"}) * 100
        or on() vector(0)
      ) < {{ .Values.alerts.thresholds.runningInstancesPercentage.critical }}
    for: {{ .Values.alerts.conditionDurations.critical }}
    labels:
      action: email
      severity: Critical {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "Pulse {{ .chart | title }} instances are down."
      information: "Detected critical number of running {{`{{ $labels.statefulset }}`}} instances: {{`{{ $value }}`}}%"

  - alert: {{ include "alertName" (merge (dict "alert" "low_running_instances") .) }}
    expr: |-
      (
        sum by (statefulset) (kube_statefulset_status_replicas_ready{namespace="{{ .Release.Namespace }}",statefulset=~"{{ include "objectName" . }}-.*"}) /
        sum by (statefulset) (kube_statefulset_status_replicas{namespace="{{ .Release.Namespace }}",statefulset=~"{{ include "objectName" . }}-.*"}) * 100
        or on() vector(0)
      ) < {{ .Values.alerts.thresholds.runningInstancesPercentage.warning }}
    for: {{ .Values.alerts.conditionDurations.warning }}
    labels:
      action: email
      severity: Warning {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "Pulse {{ .chart | title }} instances are down."
      information: "Detected low number of running {{`{{ $labels.statefulset }}`}} instances: {{`{{ $value }}`}}%"

  - alert: {{ include "alertName" (merge (dict "alert" "critical_memory") .) }}
    expr: |-
      sum by (pod) (container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",container!="",container!="POD",pod=~"{{ include "objectName" . }}-.*"}) /
      sum by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) * 100
      >= {{ .Values.alerts.thresholds.usedMemoryPercentage.critical }}
    for: {{ .Values.alerts.conditionDurations.critical }}
    labels:
      action: email
      severity: Critical {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "Detected critical memory usage by Pulse {{ .chart | title }} Pod."
      information: "Detected critical memory usage: {{`{{ $value }}`}}% by Pod: {{`{{ $labels.pod }}`}}"

  - alert: {{ include "alertName" (merge (dict "alert" "high_memory") .) }}
    expr: |-
      sum by (pod) (container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*",container!="",container!="POD"}) /
      sum by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) * 100
      >= {{ .Values.alerts.thresholds.usedMemoryPercentage.warning }}
    for: {{ .Values.alerts.conditionDurations.warning }}
    labels:
      action: email
      severity: Warning {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "Detected high memory usage by Pulse {{ .chart | title }} Pod."
      information: "Detected high memory usage: {{`{{ $value }}`}}% by Pod: {{`{{ $labels.pod }}`}}"

  - alert: {{ include "alertName" (merge (dict "alert" "critical_cpu") .) }}
    expr: |-
      sum by (pod) (rate(
        container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*",container!="",container!="POD"}[2m])) /
      sum by (pod) (
        kube_pod_container_resource_limits_cpu_cores{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) * 100
      >= {{ .Values.alerts.thresholds.usedCpuPercentage.critical }}
    for: {{ .Values.alerts.conditionDurations.critical }}
    labels:
      action: email
      severity: Critical {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "Detected critical CPU usage by Pulse {{ .chart | title }} Pod."
      information: "Detected critical CPU usage: {{`{{ $value }}`}}% by Pod: {{`{{ $labels.pod }}`}}"

  - alert: {{ include "alertName" (merge (dict "alert" "high_cpu") .) }}
    expr: |-
      sum by (pod) (rate(
        container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*",container!="",container!="POD"}[2m])) /
      sum by (pod) (
        kube_pod_container_resource_limits_cpu_cores{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) * 100
      >= {{ .Values.alerts.thresholds.usedCpuPercentage.warning }}
    for: {{ .Values.alerts.conditionDurations.warning }}
    labels:
      action: email
      severity: Warning {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "Detected high CPU usage by Pulse {{ .chart | title }} Pod."
      information: "Detected high CPU usage: {{`{{ $value }}`}}% by Pod: {{`{{ $labels.pod }}`}}"

  - alert: {{ include "alertName" (merge (dict "alert" "no_connected_senders") .) }}
    expr: (sum by (pod) (pulse_lds_senders_number{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) or on() vector(0)) == 0
    for: {{ .Values.alerts.conditionDurations.critical }}
    labels:
      action: email
      severity: Critical {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "LDS is not connected to senders."
      information: "Number of senders the LDS {{`{{ $labels.pod }}`}} is connected to: {{`{{ $value }}`}}"

  - alert: {{ include "alertName" (merge (dict "alert" "no_connected_receivers") .) }}
    expr: (sum by (pod) (pulse_lds_receivers_number{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) or on() vector(0)) == 0
    for: {{ .Values.alerts.conditionDurations.critical }}
    labels:
      action: email
      severity: Critical {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "No receivers are connected to LDS."
      information: "Number of receivers connected to the LDS {{`{{ $labels.pod }}`}}: {{`{{ $value }}`}}"

  - alert: {{ include "alertName" (merge (dict "alert" "no_registered_dns") .) }}
    expr: (sum by (pod) (pulse_lds_sender_registered_dns_number{namespace="{{ .Release.Namespace }}",pod=~"{{ include "objectName" . }}-.*"}) or on() vector(0)) == 0
    for: {{ .Values.alerts.conditionDurations.critical }}
    labels:
      action: email
      severity: Critical {{- include "alertLabels" . | nindent 6 }}
    annotations:
      summary: "No DNs are registered on LDS."
      information: "Number of DNs registered on the LDS {{`{{ $labels.pod }}`}}: {{`{{ $value }}`}}"
