# Helm chart values overrides common to all Azure Stage locations

image:
  repository: pureengage-docker-staging.jfrog.io/pulse/
  pullPolicy: Always

imagePullSecrets:
  # Name of secret for pulling image from Artifactory.
  # In Azure there are pre-created secrets pureengage-docker-dev and pureengage-docker-staging in our namespace
  - name: pureengage-docker-staging

config:
  mountSecrets: false
  postgresConfig: pulse-tf-config
  postgresSecret: pulse-tf-secret
  redisConfig: pulse-tf-config
  redisSecret: pulse-tf-secret
  gwsSecret: pulse-gws-secret
  dbName: pulse
