# Helm chart values overrides common for all Azure environments

networkPolicies:
  enabled: false
  egressports:
  # Connection to GWS
    - protocol: TCP
      port: 80

labels:
  tenant: shared
  genesysengage/monitoring: prometheus

nodeSelector:
  genesysengage.com/nodepool: general

priorityClassName: genesysengage-medium-priority

