apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "init-tenant.fullname" . }}-templates-config
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "init-tenant.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $path, $_ :=  $files.Glob  (printf "data/templates/**.gpb" ) }}
  {{- $template := (regexReplaceAll "^data/templates/([^/]+)/.*" $path "${1}") }}
  {{ regexReplaceAll "^data/templates/" $path "" | replace "/" "-" }}: |-
    {{- tpl ($files.Get $path) (merge (dict "template" $template) $) | nindent 4 }}
  {{- end }}
  templates.list: |-
    {{- range .Values.templates }}
    /data/{{ . }}
    {{- end }}
