name: Custom Actions

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, synchronize]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/greeting
        env:
          DUMMYVAR: DummyVal
        with:
          whoToGreet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
