name: Deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]
  repository_dispatch:
    types: [ deploy, deploy-abc ]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy-apply:
    if: >
      (github.event_name == 'repository_dispatch') ||
      (github.event_name == 'pull_request' && (
        github.event.pull_request.title == 'deploy' ||
        startsWith(github.event.pull_request.title, 'deploy ') ||
        startsWith(github.event.pull_request.title, 'deploy-abc')) &&
        github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Payload
        id: payload
        run: |
          set -x
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            echo "::set-output name=cmd::${{ github.event.pull_request.title }}"
          else
            echo "::set-output name=cmd::${{ github.event.client_payload.cmd }}"
          fi

      - name: Show Parameters
        run: |
          echo "cmd: ${{ steps.payload.outputs.cmd }}"

      - name: Show Parameters
        if: github.event_name == 'pull_request'
        run: |
          true

      - name: Show Parameters
        if: success()
        run: |
          echo "cmd: ${{ steps.payload.outputs.cmd }}"
