name: Deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]
  repository_dispatch:
    types: [ deploy ]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy-apply:
    if: >
      (github.event_name == 'repository_dispatch') ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'deploy') && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Payload
        id: payload
        run: |
          set -x
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            instructions="${{ github.event.pull_request.title }}"
          else
            instructions="${{ github.event.pull_request.title }}"
          fi
          echo "::set-output name=instructions::$instructions"
          case "$instructions" in
          deploy-*)
            echo "::set-output name=component::$(sed -e 's/^deploy-\([^ ]*\).*/\1/')"
            ;;
          esac

      - name: Show Parameters
        run: |
          echo "instructions: ${{ steps.payload.outputs.instructions }}"
          echo "component: ${{ steps.payload.outputs.component }}"
