name: Deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]
  repository_dispatch:
    types: [ deploy ]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy-apply:
    if: >
      (github.event_name == 'repository_dispatch') ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'deploy') && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Payload
        id: payload
        run: |
          set -x
          if [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            instructions="${{ github.event.pull_request.title }}"
            case "$instructions" in
            deploy-*)
              echo "::set-output name=component::$(echo "$instructions" | sed -e 's/^deploy-\([^ ]*\).*/\1/')"
              ;;
            esac
          else
            instructions="${{ github.event.client_payload.cmd }}"
            echo "::set-output name=component::${{ github.event.client_payload.component }}"
          fi
          echo "::set-output name=instructions::$instructions"

      - name: Show Parameters
        run: |
          echo "instructions: ${{ steps.payload.outputs.instructions }}"
          echo "component: ${{ steps.payload.outputs.component }}"

      - name: Check Parameters
        if: "!steps.payload.outputs.component || steps.payload.outputs.component == 'abc'"
        run: |
          true

      - name: Show Parameters
        if: ${{ success() }}
        run: |
          echo "instructions: ${{ steps.payload.outputs.instructions }}"
          echo "component: ${{ steps.payload.outputs.component }}"
