name: Deploy

on:
  repository_dispatch:
    types: [ test, test-fail, test-skip ]

jobs:
  start:
    if: github.event.action != 'test-skip'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Main
        run: |
          [[ "${{ github.event.action }}" != "test-fail" ]]

  end:
    needs: [ job-1, job-2 ]
    runs-on: ubuntu-latest

    steps:
      - name: Main
        run: |
          true

  job-1:
    needs: [ start ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Changes
        id: modified
        uses: actions/cache@v2
        with:
          path: |
            job-1
          key: ${{ runner.os }}-job1-${{ hashFiles('job-1') }}

      - name: Main
        if: steps.modified.outputs.cache-hit != 'true'
        run: |
          true

  job-2:
    needs: [ start ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Changes
        id: modified
        uses: actions/cache@v2
        with:
          path: |
            job-2
          key: ${{ runner.os }}-job2-${{ hashFiles('job-2') }}

      - name: Main
        if: steps.modified.outputs.cache-hit != 'true'
        run: |
          true
