name: Deploy

on:
  repository_dispatch:
    types: [ test, test-fail, test-skip ]

jobs:
  start:
    if: github.event.action != 'test-skip'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Main
        run: |
          [[ "${{ github.event.action }}" != "test-fail" ]]

  end:
    needs: [ start, job-1, job-2 ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Main
        run: |
          [[ "${{ contains(needs.*.result, 'failure') }}" == "false" ]]

  job-1:
    needs: [ start ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Changes
        id: modified
        uses: actions/cache@v2
        with:
          path: |
            job-1.lock
          key: ${{ runner.os }}-job1-${{ hashFiles('job-1') }}

      - name: Main
        if: steps.modified.outputs.cache-hit != 'true'
        run: |
          ls -al
          touch job-1.lock

  job-2:
    needs: [ start ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Changes
        id: modified
        uses: actions/cache@v2
        with:
          path: |
            job-2.lock
          key: ${{ runner.os }}-job2-${{ hashFiles('job-2') }}

      - name: Main
        if: steps.modified.outputs.cache-hit != 'true'
        run: |
          ls -al
          touch job-2.lock
