name: Deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]
  repository_dispatch:
    types: [ deploy ]

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy-apply:
    if: >
      (github.event_name == 'repository_dispatch') ||
      (github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'deploy') && github.event.pull_request.merged == true)

    runs-on: ubuntu-latest
    # outputs:
    #   instructions: ${{ github.event.pull_request.title }}${{ github.event.client_payload.cmd }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Payload
        env:
          prdata: ${{ github.event.pull_request.title }}
          rddata: ${{ github.event.client_payload.cmd }}
        id: payload
        run: |
          set -x
          [[ -n "$prdata" ]] && echo "::set-output name=data::\"$prdata\"" || echo "::set-output name=data::\"$rddata\""

      - name: Show Payload
        env:
          instructions: ${{ steps.payload.outputs.data }}
        run: |
          echo "instructions1: $instructions1"
          echo "instructions2: ${{ steps.payload.outputs.data }}"
