name: Pull Request Closed

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:

  init:
    if: >-
      github.event.pull_request.merged == true

    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          fetch-depth: 2

      - name: Check Changes
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          set -x
          echo =================
          ( set -x; git log )
          echo =================
          ( set -x; git diff --name-status HEAD~1 -- . )
          echo =================
          ( set -x; git diff --name-status ${{ github.base_ref }} -- .github )
          echo =================
          ( set -x; git diff --name-status ${{ github.base_ref }} -- ${GITHUB_WORKSPACE}/.github )
