
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

app:
  options:
    # for >= Java 10
    # https://medium.com/adorsys/usecontainersupport-to-the-rescue-e77d6cfea712
    javaOpts: -XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0
    # for < Java 10
    #javaOpts: -XX:+UseCGroupMemoryLimitForHeap
    # Http port
    httpPort: 8090
    # Name of application created for User Permissions Service on Config Server
    cfgApp: pulse-col
    # Type of application created for User Permissions Service on Config Server
    cfgAppType: 38
    # Level of logging. Can be NONE, ERROR, WARN, INFO, DEBUG
    logLevel: DEBUG
    # Expire timeout of records in Cache
    cacheTimeout: 900
    # Max number of items stored in Cache
    cacheSize: 1000000
    # Database Polling Interval
    dbPollingInterval: 60
    # Local addp timeout
    dbAddpLocalTimeout: 180
    # Remote addp timeout
    dbAddpRemoteTimeout: 190

config:
  postgresConfig: ""
  postgresSecret: ""
  redisConfig: ""
  redisSecret: ""
  # Database Name
  dbName: pulse

service:
  type: ClusterIP
  port: 80

# tenant identification, or empty for shared deployment
tenant:
  # cloud tenant ID
  id: "00000000-0000-0000-0000-000000000000"
  # cloud tenant SID (like 0001)
  sid: "0000"

# deployment parameters
deployment:
  # deployment type: local|azure (TBD more)
  type: local

image:
  name: userpermissions
  tag: ""
  pullPolicy: IfNotPresent
  repository: ""

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "500m"


priorityClassName: ""

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsUser: 500
  runAsGroup: 500
  fsGroup: 500
